server:
  port: 8082

spring:
  application:
    name: demo2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#  instance:
#    hostname: localhost